[project]
name = "dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.10.3",
    "dbt-trino>=1.9.2",
    "sqlfluff-templater-dbt>=3.4.1",
    "sqlfluff>=3.4.1",
]
